name: RIVM daily numbers per municipality

on:
  schedule:
    - cron: "*/15 12-15 * * *"

jobs:
  rivm-numbers-per-municipality:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download and dissect
      run: swift run scalpel
      
    - name: Commit files
      run: |
        git config --local user.email "marko@hungry.dev"
        git config --local user.name "infected-data Action"
        git commit -m "Updates latest RIVM data" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
