name: Download and dissect latest data

on:
  schedule:
    - cron: "25 13,15,17,19,21 * * *"
    
    workflow_dispatch:
      
      jobs:
        scalpel:
          
          runs-on: macos-latest
          
          steps:
            - uses: actions/checkout@v2
            - name: Download and dissect
              env:
                METABASE_USERNAME: ${{ secrets.METABASE_USERNAME }}
                METABASE_PASSWORD: ${{ secrets.METABASE_PASSWORD }}
              run: swift run scalpel
              
              - name: Commit files
              run: |
              git config --local user.email "marko@hungry.dev"
              git config --local user.name "infected-data Action"
              git add .
              git commit -m 'Updates latest numbers'
              
              - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: ${{ github.ref }}
