name: Download and dissect RIVM, NICE and LCPS data

on:
  schedule:
    - cron: "0 14,16,18,20,22 * * *"
  
  workflow_dispatch:


jobs:
  scalpel:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download and dissect
      run: swift run scalpel
      
    - name: Commit files
      run: |
        git config --local user.email "marko@hungry.dev"
        git config --local user.name "infected-data Action"
        git add .
        git commit -m 'Updates latest RIVM, NICE and LCPS data'

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
